name: json_store
description: A Flutter storage solution somewhat similar to a browser's localStorage (but super powered)
version: 1.0.2
author: Frans Stofberg <stofberg.dev@gmail.com>
homepage: https://github.com/fstof/flutter_json_store

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^4.0.0
  flutter_secure_storage: ^3.3.2
  path_provider: ^1.6.5
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
